### PR TITLE
[FIX] Build

### PR DESCRIPTION
**Pull request by Bagaric**
- [x] Fix an issue where `index.js` was being ignored by `.gitignore` which stops the package from being used properly when installed as a dependency to another project.
- [x] Fix `built` folder not being created after `npm install`
- [x] Fix bluebird error when building with `npm install`

### CODE REVIEW

**Comment by Bagaric** [comment]
It has it's downsides, cause I needed to move `typescript` to be a dependency, which will increase the size of the dependencies. The only way to avoid that would be commit the `built/` directory to our repo, which is not ideal either.

**Comment by adibas03** [comment]
I think the `built` might be okay, and can always be rebuilt

**Comment by lsaether** [comment]
I think having it all built into a single file as the root index.js might work. Since right now to use it you have to compile it locally anyway so now you have installed typescript maybe you didn't want and still have the built locally.

**Comment by Bagaric** [comment]
Then we would be back at using Parcel. We can consider webpack I guess.

**Pull request merged**
