### PR TITLE
Deps update. BigNumber v8

### PR DESCRIPTION
**Pull request by kosecki123**

### CODE REVIEW

**Review by e00dan — COMMENTED** [review]
Since web3 1.0 is using de facto BigNumber.js version 4, and they're using BigNumber's inside their packages, from me there's ⛔️ no on this pull request and I believe we should revert this upgrade in lib.

Because of the nature of JavaScript - especially in the dapp, where MetaMask has its own compiled web3, there's possibility of passing bignumber v8 objects to lib that was created to work with bignumber v4 and this was someting that stopped last attempt to upgrade.

As long as web3 1.0 is using BigNumber.js v4 I would stick to it. I haven't found exact place that web3 is using method that is removed in newer versions, but this is possible.

References:
https://github.com/ethereum/web3.js/blob/1.0/package-lock.json#L1230 - package.lock showing they use:
```
"bignumber.js": {
      "version": "4.1.0",
      "resolved": "https://registry.npmjs.org/bignumber.js/-/bignumber.js-4.1.0.tgz",
      "integrity": "sha512-eJzYkFYy9L4JzXsbymsFn3p54D+llV27oTQ+ziJG7WFRheJcNZilgVXMG0LoZtlQSKBsJdWtLFqOD0u+U0jZKA==",
      "dev": true
    },
```
https://github.com/ethereum/web3.js/issues/1760 - Package bignumber.js is not up-to-date issue
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/utils.js#L270 - example of web3 using BigNumber

**Comment by kosecki123** [comment]
> Since web3 1.0 is using de facto BigNumber.js version 4, and they're using BigNumber's inside their packages, from me there's ⛔️ no on this pull request and I believe we should revert this upgrade in lib.
Yes, that's true, but they are using both BigNumber.js and BN.js, so you can chose. Also this is optional and used internally, take a look at their docs, all methods are accepting string|BigNumber|BN which means that we should .toString our V8 BigNumbers before calling web3 stuff and there will be confilicts.

**Comment by Kuzirashi** [comment]
The thing is I'm not sure if we communicate with web3 by casting values to strings, for example I wasn't aware of such practice (which seems a good practice, considering problems with versions). The real test for if this upgrade works is upgrading dapp and testing with MetaMask.

**Comment by kosecki123** [comment]
Also timenode-core doesn't touch web3 directly, at least that was the idea :)

**Pull request merged**
