### PR TITLE
[FIX] Only support wallet Store

### PR DESCRIPTION
**Pull request by adibas03**

### CODE REVIEW

**Comment by kosecki123** [comment]
This PR is adding node specific 'fs' module requirement to eac.js-client. This will require extra effort in non-node environments. 

What's the reason for having other way of reading the wallet?

**Comment by adibas03** [comment]
The `fs` module only comes in when a wallet file is used, instead of a key store.
An option will be to move the require for fs into the if condition.
Though, I do not know about that

**Comment by kosecki123** [comment]
Why not add fs.readFileSync(opts.walletFile, 'utf8'); in eac.js-cli and leave eac.js-client as it was ?

**Comment by kosecki123** [comment]
Reading wallet from the file is a specific why to initialise the wallet, whole point of have higher level abstraction is to be open for other ways to deliver the wallet. That's why we just keep the way to pass it as keystore, so browser will read from localStorage, cli from file etc

**Comment by adibas03** [comment]
implementing suggested separation of concerns.  
wil update when ready

**Comment by adibas03** [comment]
@kosecki123 @lsaether ready. Kindly re-review

**Pull request merged**
